---
- name: restart rsyslog
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop: "{{ rsyslog_services | flatten }}"
  when: rsyslog_enable is true
  listen: restart_rsyslog
